version: '2'
services:
  go-web-app:
    restart: always
    container_name: go_app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=flavioespinoza.com
      - LETSENCRYPT_HOST=flavioespinoza.com